---
- name: Patch restricted security context
  shell: KUBECONFIG={{ lookup('env', 'WORKSPACE') }}/kubeconfig kubectl patch scc restricted -p '{{ item }}'
  with_items:
    - '{"allowHostDirVolumePlugin": true}'
    - '{"allowHostNetwork": true}'
    - '{"allowHostIPC": true}'
    - '{"allowHostPorts": true}'
    - '{"allowPrivilegedContainer": true}'
    - '{"allowedCapabilities": ["DAC_READ_SEARCH", "SYS_RESOURCE", "CAP_NET_RAW", "CAP_NET_ADMIN"]}'
    - '{"requiredDropCapabilities": ["KILL", "MKNOD"]}'
    - '{"runAsUser": {"type": "RunAsAny" }}'
    - '{"seLinuxContext": {"type": "RunAsAny"}}'
    - '{"volumes": ["configMap", "downwardAPI", "emptyDir", "hostPath", "persistentVolumeClaim", "projected", "secret", "nfs"]}'

- name: Label master nodes
  shell: KUBECONFIG={{ lookup('env', 'WORKSPACE') }}/kubeconfig kubectl label nodes testcluster-api {{ item }}
  with_items:
    - "app=nfs-provisioner"
    - "role=master"
    - "openstack-control-plane=enabled"
  ignore_errors: true

- name: Deploy the NFS manifests
  shell: KUBECONFIG={{ lookup('env', 'WORKSPACE') }}/kubeconfig kubectl apply -f {{ lookup('env', 'WORKSPACE') }}/edge-poc-netlab/third-party/external-storage/nfs-client/deploy/{{ item }}
  with_items:
    - rbac.yaml
    - deployment.yaml
    - class.yaml

- name: Deploy the mysql manifests
  shell: KUBECONFIG={{ lookup('env', 'WORKSPACE') }}/kubeconfig kubectl apply -f {{ lookup('env', 'WORKSPACE') }}/edge-poc-netlab/third-party/mysql-operator/deploy/{{ item }}
  with_items:
    - rbac.yaml
    - role-binding-template.yaml
    - custom-resource-definitions.yaml
    - role-agent.yaml
    - mysql-deployment.yaml

- name: Deploy the dhcp manifests
  shell: KUBECONFIG={{ lookup('env', 'WORKSPACE') }}/kubeconfig kubectl apply -f {{ lookup('env', 'WORKSPACE') }}/edge-poc-netlab/third-party/dhcp/deploy/{{ item }}
  with_items:
    - configmap.yaml
    - dhcp-service.yaml
    - deployment.yaml

- name: Deploy the rabbitmq manifests
  shell: KUBECONFIG={{ lookup('env', 'WORKSPACE') }}/kubeconfig kubectl apply -f {{ lookup('env', 'WORKSPACE') }}/edge-poc-netlab/third-party/rabbitmq/deploy/{{ item }}
  with_items:
    - rabbitmq_rbac.yaml
    - rabbitmq_statefulsets.yaml

- name: Deploy the ironic manifests
  shell: KUBECONFIG={{ lookup('env', 'WORKSPACE') }}/kubeconfig kubectl apply -f {{ lookup('env', 'WORKSPACE') }}/edge-poc-netlab/third-party/ironic/deploy/{{ item }}
  with_items:
    - cluster-with-volume.yaml
    - configmap-etc.yaml
    - configmap-bin.yaml
    - secret-db-admin.yaml
    - secret-rabbitmq.yaml
    - job-db-init.yaml
    - job-db-sync.yaml
    - job-rabbit-init.yaml
    - deployment-api.yaml
    - service-api.yaml
    - statefulset-conductor.yaml
    - service-tftp.yaml
    - service-http.yaml
