---
# tasks file for netlab
#
- name: set role supported functions
  set_fact:
    netlab_functions:
      - provision
      - build
      - shutdown
      - destroy
      - terminate
      - noop

- name: validate the requested function is supported
  fail:
    msg: "invalid function specified, expected one of {{ eos_functions }}, got {{ function }}"
  when: function | default('noop') not in netlab_functions

- name: include function specific tasks and run
  include_tasks: "{{ function  | default('noop') }}.yaml"
