# Tasks to prepare the provisioning host
---
- name: Start nfs services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - rpcbind
    - nfs-server

- name: Create the directory to be shared by NFS and give permissions
  file:
    path: /var/nfs
    owner: nfsnobody
    group: nfsnobody
    mode: 0755

- name: Remove content inside nfs directory
  shell: /bin/rm -rf /var/nfs/*
  ignore_errors: true

- name: Generate exports file
  copy:
    dest: /etc/exports
    content: "/var/nfs *(rw,no_root_squash,sync)"

- name: Restart nfs server to pick exports
  service:
    name: nfs-server
    enabled: yes
    state: restarted

- name: Enable firewall rules
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  with_items:
    - rpc-bind
    - nfs
    - dhcp

- name: Enable firewall ports
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  with_items:
    - 5672/tcp
    - 15672/tcp
    - 8081/tcp
