apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dhcp-server
  labels:
    app: dhcp-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dhcp-server
    spec:
      hostNetwork: true
      containers:
        - name: dhcp-server
          image: networkboot/dhcpd:latest
          imagePullPolicy: Always
          #command: ["/bin/bash", "-", "sleep 86400"]
          ports:
            - containerPort: 67
              hostPort: 67
              protocol: UDP
          volumeMounts:
            - name: dhcp-server
              mountPath: /data/dhcpd.conf
              subPath: mymounts/dhcpd.conf
      volumes:
        - name: dhcp-server
          configMap:
            name: dhcp-server
            items:
             - key: config
               path: mymounts/dhcpd.conf
