---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ironic-api
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: rocky-ironic-api
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rocky-default-ironic-api
subjects:
  - kind: ServiceAccount
    name: ironic-api
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: rocky-default-ironic-api
  namespace: default
rules:
  - apiGroups:
      - ""
      - extensions
      - batch
      - apps
    verbs:
      - get
      - list
    resources:
      - services
      - endpoints
      - jobs
      - pods
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ironic-api
  labels:
    release_group: rocky
    application: ironic
    component: api
spec:
  replicas: 1
  selector:
    matchLabels:
      release_group: rocky
      application: ironic
      component: api
  template:
    metadata:
      labels:
        release_group: rocky 
        application: ironic
        component: api
    spec:
      serviceAccountName: ironic-api
      nodeSelector:
        openstack-control-plane: enabled
      initContainers:
        
        
        - name: init
          image: "quay.io/stackanetes/kubernetes-entrypoint:v0.3.1"
          imagePullPolicy: IfNotPresent
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: INTERFACE_NAME
              value: eth0
            - name: PATH
              value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/
            - name: DEPENDENCY_DAEMONSET
              value: ""
            - name: DEPENDENCY_CONTAINER
              value: ""
            - name: DEPENDENCY_POD_JSON
              value: ""
            - name: COMMAND
              value: "echo done"
          command:
            - kubernetes-entrypoint
          volumeMounts:
            null

      containers:
        - name: ironic-api
          image: "quay.io/yrobla/tripleorocky-centos-binary-ironic-api"
          imagePullPolicy: IfNotPresent
          
          command:
            - /tmp/ironic-api.sh
            - start
          lifecycle:
            preStop:
              exec:
                command:
                  - /tmp/ironic-api.sh
                  - stop
          ports:
            - containerPort: 6385
          readinessProbe:
            tcpSocket:
              port: 6385
          volumeMounts:
            - name: ironic-bin
              mountPath: /tmp/ironic-api.sh
              subPath: ironic-api.sh
              readOnly: true
            - name: ironic-etc
              mountPath: /etc/ironic/ironic.conf
              subPath: ironic.conf
              readOnly: true
            - name: ironic-etc
              mountPath: /etc/ironic/logging.conf
              subPath: logging.conf
              readOnly: true
            - name: ironic-etc
              mountPath: /etc/ironic/policy.json
              subPath: policy.json
              readOnly: true
            - name: pod-shared
              mountPath: /tmp/pod-shared
      volumes:
        - name: ironic-bin
          configMap:
            name: ironic-bin
            defaultMode: 0555
        - name: ironic-etc
          configMap:
            name: ironic-etc
            defaultMode: 0444
        - name: pod-shared
          emptyDir: {}
