---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ironic-db-sync
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: rocky-ironic-db-sync
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rocky-default-ironic-db-sync
subjects:
  - kind: ServiceAccount
    name: ironic-db-sync
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: rocky-default-ironic-db-sync
  namespace: default
rules:
  - apiGroups:
      - ""
      - extensions
      - batch
      - apps
    verbs:
      - get
      - list
    resources:
      - services
      - endpoints
      - jobs
      - pods
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "ironic-db-sync"
spec:
  template:
    metadata:
      labels:
        release_group: rocky 
        application: ironic
        component: db-sync
    spec:
      serviceAccountName: ironic-db-sync
      restartPolicy: OnFailure
      nodeSelector:
        openstack-control-plane: enabled
        
      initContainers:
        
        - name: init
          image: "quay.io/stackanetes/kubernetes-entrypoint:v0.3.1"
          imagePullPolicy: IfNotPresent
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: INTERFACE_NAME
              value: eth0
            - name: PATH
              value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/
            - name: DEPENDENCY_JOBS
              value: "ironic-db-init"
            - name: DEPENDENCY_DAEMONSET
              value: ""
            - name: DEPENDENCY_CONTAINER
              value: ""
            - name: DEPENDENCY_POD_JSON
              value: ""
            - name: COMMAND
              value: "echo done"
          command:
            - kubernetes-entrypoint
          volumeMounts:
            []
            
      containers:
        - name: "ironic-db-sync"
          image: "quay.io/yrobla/tripleorocky-centos-binary-ironic-api"
          imagePullPolicy: "IfNotPresent"
          
          command:
            - /tmp/db-sync.sh
          volumeMounts:
            - name: db-sync-sh
              mountPath: /tmp/db-sync.sh
              subPath: db-sync.sh
              readOnly: true
            - name: etc-service
              mountPath: "/etc/ironic"
            - name: db-sync-conf
              mountPath: "/etc/ironic/ironic.conf"
              subPath: "ironic.conf"
              readOnly: true
            - name: db-sync-conf
              mountPath: "/etc/ironic/logging.conf"
              subPath: "logging.conf"
              readOnly: true
      volumes:
        - name: db-sync-sh
          configMap:
            name: "ironic-bin"
            defaultMode: 0555
        - name: etc-service
          emptyDir: {}
        - name: db-sync-conf
          configMap:
            name: "ironic-etc"
            defaultMode: 0444

