---
apiVersion: v1
kind: Secret
metadata:
  name: ironic-rabbitmq-admin
type: Opaque
data:
  RABBITMQ_CONNECTION: cmFiYml0Oi8vZ3Vlc3Q6Z3Vlc3RAcmFiYml0bXE6MTU2NzIvaXJvbmlj
---
apiVersion: v1
kind: Secret
metadata:
  name: ironic-rabbitmq-user
type: Opaque
data:
  RABBITMQ_CONNECTION: cmFiYml0Oi8vaXJvbmljOnBhc3N3b3JkQHJhYmJpdG1xOjE1NjcyL2lyb25pYw==
