---
apiVersion: v1
kind: Secret
metadata:
  name: ironic-db-admin
type: Opaque
data:
  DB_HOST: bXlzcWw=
  DB_USER: cm9vdA==
  DB_PASSWORD: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: ironic-db-user
type: Opaque
data:
  DB_HOST: bXlzcWw=
  DB_USER: aXJvbmlj
  DB_PASSWORD: cGFzc3dvcmQ=
  DB_DATABASE: aXJvbmlj
