---
apiVersion: v1
kind: Service
metadata:
  name: ironic-api
spec:
  type: NodePort
  ports:
    - name: m-api
      protocol: TCP
      port: 6385
      nodePort: 32732
    
  selector:
    release_group: queens
    application: ironic
    component: api

